package main

var uiPage = []byte(`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Grok SSO Importer</title><style>
body{font-family:system-ui,sans-serif;background:#0b1020;color:#e8edf8;margin:0}.wrap{max-width:1050px;margin:30px auto;padding:0 18px}.card{background:#151c30;border:1px solid #2b3551;border-radius:14px;padding:20px;margin:16px 0}.row{display:flex;gap:12px;flex-wrap:wrap;align-items:center}textarea,input,select{background:#0f1628;color:#fff;border:1px solid #3a4668;border-radius:8px;padding:10px}textarea{width:100%;box-sizing:border-box;min-height:220px}input[type=password],input[type=text]{min-width:260px}button{background:#5b8cff;color:#fff;border:0;border-radius:9px;padding:10px 18px;font-weight:700;cursor:pointer}button:disabled{opacity:.5}table{width:100%;border-collapse:collapse}th,td{padding:9px;border-bottom:1px solid #29324d;text-align:left;font-size:14px}.ok{color:#65d39a}.bad{color:#ff8290}.muted{color:#98a3bf}
</style></head><body><div class="wrap"><h1>Grok SSO Importer</h1><p class="muted">One SSO per line. Also accepts email----password----sso lines.</p>
<div class="card"><div class="row"><input id="key" type="password" placeholder="CPA Management Key"><input id="file" type="file" accept=".txt,text/plain"><select id="workers"><option>1</option><option selected>2</option><option>3</option><option>4</option></select><input id="proxy" type="text" placeholder="Optional proxy URL"></div><p><textarea id="content" placeholder="Paste SSO tokens here, one per line"></textarea></p><div class="row"><button id="start">Convert and import</button><span id="progress" class="muted"></span></div><p id="message" class="bad"></p></div>
<div class="card"><table><thead><tr><th>#</th><th>Result</th><th>Credential file</th><th>Email / subject</th><th>Error</th></tr></thead><tbody id="rows"></tbody></table></div></div><script>
const api='/v0/management/plugins/grok-sso-importer';const key=document.querySelector('#key');key.value=localStorage.getItem('groksso-key')||'';
function headers(json){localStorage.setItem('groksso-key',key.value);let h={'Authorization':'Bearer '+key.value,'X-Management-Key':key.value};if(json)h['Content-Type']='application/json';return h}
async function call(path,opt){opt=opt||{};let r=await fetch(api+path,{...opt,headers:headers(!!opt.body)});let d=await r.json();if(!r.ok)throw new Error(d.error||r.statusText);return d}
document.querySelector('#file').onchange=async function(e){let f=e.target.files&&e.target.files[0];if(f)document.querySelector('#content').value=await f.text()};
function esc(v){return String(v||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function render(s){document.querySelector('#start').disabled=s.running;document.querySelector('#progress').textContent=s.running?('Running '+s.done+'/'+s.total):('Success '+s.success+', failed '+s.failed);document.querySelector('#rows').innerHTML=(s.results||[]).map(function(r){return '<tr><td>'+r.index+'</td><td class="'+(r.ok?'ok':'bad')+'">'+(r.ok?'OK':'Failed')+'</td><td>'+esc(r.file_name)+'</td><td>'+esc(r.email||r.subject)+'</td><td class="bad">'+esc(r.error)+'</td></tr>'}).join('')}
async function refresh(){try{let s=await call('/status');render(s);if(s.running)setTimeout(refresh,1000)}catch(e){document.querySelector('#message').textContent=e.message}}
document.querySelector('#start').onclick=async function(){let content=document.querySelector('#content').value;if(!content.trim()){document.querySelector('#message').textContent='Paste tokens or select a TXT file first.';return}if(!confirm('SSO values will be sent only to this CPA server for conversion. Continue?'))return;try{document.querySelector('#message').textContent='';await call('/import',{method:'POST',body:JSON.stringify({content:content,workers:Number(document.querySelector('#workers').value),proxy:document.querySelector('#proxy').value})});document.querySelector('#content').value='';refresh()}catch(e){document.querySelector('#message').textContent=e.message}};refresh();
</script></body></html>`)
